### ISSUE TITLE
Error with links without text

### ISSUE THREAD

**Issue by bleutzinn** [HuidaeCho/grav-plugin-markdown-yalinker#1]
Very interesting plugin!

However when I tried it and used a link without text like `[[My page]]` I got a "Undefined offset: 2" error at line 39.

That line should be:
```
if (isset($matches[2])) {
```

**Comment by HuidaeCho** [comment]
Hmm.. maybe, it's the PHP version. Let me take the conservative approach. Thanks for reporting this issue.

**Comment by bleutzinn** [comment]
FYI I'm using PHP Version 7.1.33. I need to upgrade I guess :)

**Comment by HuidaeCho** [comment]
Have you tried `strlen($matches[2])` instead of `isset($matches[2])`? I need to make sure that `$matches[2]` contains characters, not just defined empty. It would be less function calls than `isset($matches[2]) && strlen($matches[2])` if that works.

**Comment by HuidaeCho** [comment]
Well, that line.. if `$matches[2]` is set, it cannot be empty because of `+` in the regex. I'm looking at line 84, which can be empty.

**Comment by HuidaeCho** [comment]
Just committed a fix. Please test it again. Thanks!

**Comment by HuidaeCho** [comment]
For our records, my PHP version is 7.2.32.

**Comment by bleutzinn** [comment]
Line 39 is still causing problems. For ```strlen($matches[2])``` to work the array ```$matches``` must contain at least 3 items. And when using a link without text ```$matches``` is just 2 items long.

**Comment by HuidaeCho** [comment]
I see. I need to better understand how PHP handles optional (`?`) matches.

**Comment by HuidaeCho** [comment]
Maybe, it's a PHP setting. This code runs fine on my server even though `$x` was never defined. It prints `NOT SET`. Anyway, I added `isset($matches[2])`.
```php
<?php
if($x[2])
    print("SET\n");
else
    print("NOT SET\n");
```

**Comment by HuidaeCho** [comment]
Separate from that, this is good to know, I think:
```php
<?php
$str = "a";

# $matches[2] is set to an empty string because (b?) itself is not optional
preg_match("/(a?)(b?)/", $str, $matches);
print_r($matches);
if($matches[2] === "")print("empty string\n");

# $matches[2] is NOT set because (b) is optional and the last group;
# the array stops before this non-match
preg_match("/(a)?(b)?/", $str, $matches);
print_r($matches);
if($matches[2] === "")print("empty string\n");
```
outputs
```php
Array
(
    [0] => a
    [1] => a
    [2] => 
)
empty string
Array
(
    [0] => a
    [1] => a
)
```
However, if an empty match is not the last one, it is set to an empty string. It has to be because of the following matches in the array. It cannot be left undefined.
```php
<?php
$str = "b";

# (a?) doesn't exist, but $matches[1] is set to an empty string
preg_match("/(a?)(b?)/", $str, $matches);
print_r($matches);
if($matches[1] === "")print("empty string\n");

# (a) is optional, but still $matches[1] has to be set to an empty string
# because of the following matches in the array
preg_match("/(a)?(b)?/", $str, $matches);
print_r($matches);
if($matches[1] === "")print("empty string\n");
```
outputs
```php
isgreat ~$ php a.php 
Array
(
    [0] => b
    [1] => 
    [2] => b
)
empty string
Array
(
    [0] => b
    [1] => 
    [2] => b
)
empty string
```

**Comment by HuidaeCho** [comment]
> Line 39 is still causing problems. For `strlen($matches[2])` to work the array `$matches` must contain at least 3 items. And when using a link without text `$matches` is just 2 items long.

Back to your suggestion `isset($matches[2])` only because if it's defined, it cannot be empty (`.+?`). Thanks for testing.

**Comment by bleutzinn** [comment]
I've tested and it's working fine now. Even with PHP 7.1.33.
